project: "WeatherBot"
fixed_model_name: "nlu_mitie_svm_model"
pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor.dat"
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"
  C: [1, 2, 5, 10, 20, 100]
  kernel: "linear"
language: "en"
cors_origins:
- "*"
